name: doc-validator
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  doc-validator:
    if: github.repository == 'grafana/agent'
    runs-on: ubuntu-latest
    container:
      image: grafana/doc-validator:v3.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run doc-validator tool
        # Only run doc-validator on specific directories.
        run: >
          doc-validator
          '--skip-checks=^(?:image.+)$'
          ./docs/sources
          /docs/grafana/latest
          | reviewdog
          -f=rdjsonl
          --fail-on-error
          --filter-mode=nofilter
          --name=doc-validator
          --reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
